version: '3.9'
services:
  api:
    build: .
    ports:
      - '3000:3000'
    environment:
      - MONGODB_URI=mongodb://mongo:27017/ledgr
      - JWT_SECRET=${JWT_SECRET}
      - EXCHANGE_RATE_API_KEY=${EXCHANGE_RATE_API_KEY}
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:7
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
